name: Generate Changelog
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git and Switch to Main
      run: |
        git config user.name 'Veloera Bot'
        git config user.email 'github-bot@veloera.org'
        
        git fetch origin main
        git checkout -B main origin/main
        git pull origin main
    
    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Commit and Push Changes
      run: |
        git add CHANGELOG.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "docs: :robot: changelog file generated"
          git push origin main
        fi